
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("vendor/phantom-js/breakpoints.min.js")
require("vendor/phantom-js/browser.min.js")
require("vendor/phantom-js/main.js")
require("vendor/phantom-js/util.js")

require("vendor/parallelism-js/jquery.poptrox.min.js")
require("vendor/parallelism-js/breakpoints.min.js")
require("vendor/parallelism-js/main.js")
require("vendor/parallelism-js/util.js")